import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'


export default function Home() {
  const [usersList,setUsersList] = useState([])

  async function getUsers(){
    const res = await fetch('/api/listUser')
    const users = await res.json()
    setUsersList(users)
  }
  
  async function addUser(){
    const res = await fetch('/api/addUser')
    const users = await res.json()
    console.log(users)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={() => getUsers()}>click to get users</button>
      <button onClick={() => addUser()}>add user</button>

      {
        usersList.map((item,index) => (
          <div key={item.id}>
            <h1>email: {item.email}</h1>
            <h2>password: {item.password}</h2>
          </div>
        ))
      }
    </div>
  )
}
